### PR TITLE
Ascension changes

### PR DESCRIPTION
**Pull request by PaulKPetersonCO**
Updated mindlink effects to remove non-burst bonuses. Updated dat and yaml files for new SDE

### CODE REVIEW

**Comment by Slivo-fr** [comment]
Thanks !

**Comment by Slivo-fr** [comment]
Did you handle effects pf those new modules, and the related charges ?

**Comment by PaulKPetersonCO** [comment]
I think the base effect is still good. I did not see a new attribute listed. I did not do anything with charges yet.

**Comment by Slivo-fr** [comment]
Allright, the charges now define what bonus will be given by the command burst.
It should be close to the sensor booster in the way it works.
Do you want to work on this part too ?

**Pull request merged**
