### PR TITLE
Convert CREST package to a new ESI package.

### PR DESCRIPTION
**Pull request by warlof**
Replace all CREST usage with ESI.

### CODE REVIEW

**Comment by Slivo-fr** [comment]
I just tested it, could you please add a dependency so it's build with the main EveHQ project ?
Everything else seems good. Thanks for your help !

**Comment by warlof** [comment]
which dependency ?
You mean add ESI to EveHQ instead Prism ?!

**Comment by Slivo-fr** [comment]
When I built the project, ESI project was not built and VS throw me an error because it didn't found the related dll. Adding a dependency somewhere would ensure ESI build is done and VS don't show any error.

**Comment by warlof** [comment]
therefore, the reference is in Prism : https://github.com/Slivo-fr/EveHQ/pull/140/files#diff-8f923244194fcb3c4fe96b1f2e59772aR408 ?!

**Comment by Slivo-fr** [comment]
I'll try to see why it didn't build on my side, thanks for your work :)

**Pull request merged**
