### PR TITLE
Addstructurestofitter

### PR DESCRIPTION
**Pull request by PaulKPetersonCO**
Add structures to fitter
Get citadel assets

### CODE REVIEW

**Comment by Slivo-fr** [comment]
Thanks ! 

Splitting citadels assets and structure fitter into their own PR would have made things easier but that's fine :D

I'll test all this asap

**Comment by PaulKPetersonCO** [comment]
I know, sorry. started working on assets after structures and then never had time to pull them apart. The structure fitting window's security status selector is not actually wired up yet to modify structure rig attributes. That was next on my list, but wanted to get this up to be looked at.

**Comment by Slivo-fr** [comment]
Great.
The structure fitter will be release in a beta state anyway :)

**Comment by Slivo-fr** [comment]
So, structure fitter seems stable enough to be shipped as it is.
The asset viewer however look like it still need some work : 

image

Could you quickly explain what you had in mind and what's left to do ?

**Comment by Slivo-fr** [comment]
Prism is really slow to load once I merge this, any idea why ?

**Pull request merged**
