### PR TITLE
Command and Foreman Burst Charge

### PR DESCRIPTION
**Pull request by PaulKPetersonCO**
Effects changes - not tested and not hooked into remote effects yet, boosting ship should see effects if applicable I believe

### CODE REVIEW

**Comment by Slivo-fr** [comment]
I will test this on my end, thanks !

**Comment by PaulKPetersonCO** [comment]
Need to find a way to display better attributes for the bursts and charges than the warfareBuff1... types.

**Comment by Slivo-fr** [comment]
Maybe we could just change the display name in the database, in the cache creator

**Comment by Slivo-fr** [comment]
Could you please remove the dat files ? I removed them from the git so we won't have the problem again.
Sorry about this

**Comment by PaulKPetersonCO** [comment]
Do you want me to try to back out the Traits.dat and modules.dat that are in the pull request now? Or just leave dat files out of future pulls?

**Comment by Slivo-fr** [comment]
It's good :D
I was just no able to merge

**Comment by Slivo-fr** [comment]
#93

**Pull request merged**
